### PR TITLE
Added gift

### PR DESCRIPTION
**Pull request by ismaro3**
I finished the AngularJS frontend.
Please read "README.md" of my master branch for instructions.

### CODE REVIEW

**Comment by fjlopez** [comment]
I can't make it work. I have always [this error](https://docs.angularjs.org/error/$injector/modulerr?p0=starter&p1=Error:%20%5B$injector:nomod%5D%20http:%2F%2Ferrors.angularjs.org%2F1.3.15%2F$injector%2Fnomod%3Fp0%3Dstarter%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:6:417%0A%20%20%20%20at%20file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:21:412%0A%20%20%20%20at%20a%20(file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:21:53)%0A%20%20%20%20at%20file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:21:296%0A%20%20%20%20at%20file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:35:46%0A%20%20%20%20at%20r%20(file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:7:302)%0A%20%20%20%20at%20g%20(file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:34:399)%0A%20%20%20%20at%20ab%20(file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:38:135)%0A%20%20%20%20at%20d%20(file:%2F%2F%2FUsers%2Fjavier%2FDownloads%2FLaboratory-4-WebSockets-master%2Fwebapp%2Fjs%2Fdependencies%2Fangular.min.js:17:381).

**Comment by fjlopez** [comment]
In addition, you should use the plugin [Application](https://docs.gradle.org/current/userguide/application_plugin.html) so the java server can be run with `gradle run`

**Comment by ismaro3** [comment]
Done. I solved the AngularJS problem, and added Application plugin to build.gradle.

**Comment by fjlopez** [comment]
The code is OK. I'll give you the :gift:. I will modify the README.md file. It is not necessary to send a pull request again.

**Pull request closed without merging**
